image: golang
stages:
  - compile
  - test
  - package

compile:
  stage: compile
  script: go build 
  artifacts:
    paths:
    - fpinger
    expire_in: 20 minutes
  
test:
  stage: test
  script: go test
  
pack-gz:
  stage: package
  script: gzip fpinger
  artifacts:
    paths:
    - fpinger.gz
